test.out: testPacketHandler.cpp packet.cpp packetHandler.cpp message.cpp crc.cpp packet.h packetHandler.h message.h crc.h
	g++ testPacketHandler.cpp packet.cpp packetHandler.cpp message.cpp crc.cpp -o test.out

clean:
	rm -rfv *.o *.out
